trial_name: "evaluation"

seed: 100
n_seeds: 5
jit: true
headless: true
save_video: true
video_text: true
steps_per_episode: 550
debug: false
with_state_estimation: true
camera_kwargs:
        distance: 1.6
        azimuth: 45.0
        elevation: -20.0

ckpt_dirs:
  - "./Trained_models/Primary/Ckpt/Lipschitz_2025-07-14_15-48-44"
ckpt_names:
  - "Example SNS MLP"
steps: [12500]

nn_policy_type: "spline_shooter"
nn_policy_kwargs:
        n_linesearch_steps: 16
        n_iters: 1
        spline_order: 1
        n_knots: 6
        qp_alpha_init: 1.0
        lm_damping: 0 
        _lambda_init: 0.0 #0.25
        rho_init: 1.0 #1.0

        verbose: False
                 
